- hosts: ca
  gather_facts: no
  become: yes
  become_method: doas
  vars:
    ansible_user: olivier
  tasks:
    - name: Install Python on Alpine
      raw: test -e /usr/bin/python3 || apk add --no-cache python3
      changed_when: false
      