---

- name: upgrade/update apt based hosts
  hosts: all
  become: yes
  tasks:
  - include_tasks: apt-upgrade-tasks.yml
    tags: always

  - name: Install vim
    apt:
      name: vim
      state: present
    tags: always
