- name: Install Certificate Authority software
  hosts: cert_authority
  become: yes
  tasks:
  - name: Set hostname
    hostname:
      name: "ca.metatao.net"
    tags: [config, hostname]

  - name: Set timezone to UTC
    timezone:
      name: UTC
    tags: [config, timezone]

  - include_tasks: tasks/apt-upgrade-tasks.yml
    tags: [system, apt]

  - include_tasks: tasks/vim-task.yml
    tags: [tools, editor]

  - include_tasks: tasks/yubikey-task.yml
    tags: [security, yubikey]

  - include_tasks: tasks/step-cli-task.yml
    tags: [ca, step-cli]

  - include_tasks: tasks/step-ca-task.yml
    tags: [ca, step-ca]

  - include_tasks: tasks/tools-task.yml
    tags: [tools, system-tools]

  - include_tasks: tasks/ntp-task.yml
    tags: [system, ntp]

  - include_tasks: tasks/i2c-task.yml
    tags: [hardware, i2c]

  - include_tasks: tasks/info-display-task.yml
    tags: [hardware, display]

  - include_tasks: tasks/infnoise-task.yml
    tags: [security, hardware, infnoise]