- name: upgrade/update apt based hosts
  hosts: all
  become: yes
  vars:
    ansible_user: olivier
  tasks:
    - name: install cluster
      include_tasks: cluster/k3s-server.yml
      tags: always
      when: inventory_hostname == 'white'

    - name: install agent
      include_tasks: cluster/k3s-agent.yml
      tags: always
      when: inventory_hostname == 'orange' or inventory_hostname == 'pink'

    - name: install k3s dashboard
      include_tasks: cluster/k3s-dashboard.yml
      tags: always
      when: inventory_hostname == 'white'

