- name: Install basic software on cluster nodes
  hosts: cluster
  become: yes
  handlers:
    - name: restart ssh
      systemd:
        name: ssh
        state: restarted
  tasks:
  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}.metatao.net"
    tags: [config, hostname]

  - name: Set timezone to UTC
    timezone:
      name: UTC
    tags: [config, timezone]

  - include_tasks: tasks/apt-upgrade-tasks.yml
    tags: [system, apt]

  - include_tasks: tasks/vim-task.yml
    tags: [tools, editor]

  - include_tasks: tasks/tools-task.yml
    tags: [tools, system-tools]

  - include_tasks: tasks/ntp-task.yml
    tags: [system, ntp]

  - include_tasks: tasks/step-cli-task.yml
    tags: [security, step-cli]

  - include_tasks: tasks/rust-task.yml
    tags: [dev, rust]

  - include_tasks: tasks/rust-cargo-task.yml
    tags: [dev, rust, cargo]

  - include_tasks: tasks/i2c-task.yml
    tags: [hardware, i2c]

  - include_tasks: tasks/info-display-task.yml
    tags: [hardware, display]

  - include_tasks: tasks/ssh-cert-task.yml
    tags: [security, ssh, certificates]
