- name: upgrade/update apt based hosts
  hosts: ca
  become: yes
  vars:
    ansible_user: olivier
  tasks:
  - name: Set hostname
    hostname:
      name: "ca.metatao.net"
    tags: always

  - name: Set timezone to UTC
    timezone:
      name: UTC
    tags: always

  - include_tasks: tasks/apt-upgrade-tasks.yml
    tags: always

  - include_tasks: tasks/vim-task.yml
    tags: always

  - include_tasks: tasks/yubikey-task.yml
    tags: always

  - include_tasks: tasks/step-cli-task.yml
    tags: always

  - include_tasks: tasks/step-ca-task.yml
    tags: always

  - include_tasks: tasks/tools-task.yml
    tags: always

  - include_tasks: tasks/ntp-task.yml
    tags: always

  - include_tasks: tasks/i2c-task.yml
    tags: always

  - include_tasks: tasks/info-display-task.yml
    tags: always
  
  - include_tasks: tasks/infnoise-task.yml
    tags: always