- name: upgrade/update apt based hosts
  hosts: ca
  become: yes
  vars:
    ansible_user: olivier
  tasks:
  - name: Set hostname
    hostname:
      name: "ca.metatao.net"
    tags: always

  - name: Set timezone to UTC
    timezone:
      name: UTC
    tags: always

  - include_tasks: software/apt-upgrade-tasks.yml
    tags: always

  - include_tasks: software/vim-task.yml
    tags: always

  - include_tasks: software/yubikey-task.yml
    tags: always

  - include_tasks: software/step-cli-task.yml
    tags: always

  - include_tasks: software/step-ca-task.yml
    tags: always

  - include_tasks: software/tools-task.yml
    tags: always

  - include_tasks: software/ntp-task.yml
    tags: always

  - include_tasks: software/i2c-task.yml
    tags: always

  - include_tasks: software/info-display-task.yml
    tags: always
  