- name: Install basic software on cluster nodes
  hosts: white,pink,orange
  become: yes
  vars:
    ansible_user: olivier
  tasks:
  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}.metatao.net"
    tags: always

  - name: Set timezone to UTC
    timezone:
      name: UTC
    tags: always

  - include_tasks: tasks/apt-upgrade-tasks.yml
    tags: always

  - include_tasks: tasks/vim-task.yml
    tags: always

  - include_tasks: tasks/tools-task.yml
    tags: always

  - include_tasks: tasks/ntp-task.yml
    tags: always

  - include_tasks: tasks/rust-task.yml
    tags: always

  - include_tasks: tasks/rust-cargo-task.yml
    tags: always

  - include_tasks: tasks/i2c-task.yml
    tags: always

  - include_tasks: tasks/info-display-task.yml
    tags: always
