---
- name: Install K3s Agents
  hosts: pink,orange
  become: yes
  tasks:
    - name: Download K3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'

    - name: Create directory for K3s config
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: '0755'

    - name: Copy agent config  
      copy:
        src: /tmp/k3s-agent-config
        dest: /etc/rancher/k3s/config.yaml
        mode: '0600'

    - name: Install K3s Agent
      shell: /tmp/k3s-install.sh agent
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s agent to be ready
      shell: systemctl is-active k3s-agent
      register: k3s_agent_ready
      retries: 30
      delay: 10
      until: k3s_agent_ready.rc == 0 