- name: upgrade/update apt based hosts
  hosts: all
  become: yes
  vars:
    ansible_user: olivier
  tasks:
  - include_tasks: software/apt-upgrade-tasks.yml
    tags: always

  - include_tasks: software/vim-task.yml
    tags: always

  - include_tasks: software/rust-task.yml
    tags: always

  - include_tasks: software/rust-cargo-task.yml
    tags: always

  - include_tasks: software/helm-task.yml
    tags: always

  - include_tasks: software/i2c-task.yml
    tags: always

  - include_tasks: software/yubikey-task.yml
    tags: always

  - include_tasks: software/step-cli-task.yml
    tags: always

  - include_tasks: software/tools-task.yml
    tags: always

  - include_tasks: software/certbot-task.yml
    tags: always

  - include_tasks: software/info-display-task.yml
    tags: always