---

- name: upgrade/update apt based hosts
  hosts: all
  become: yes
  vars:
    ansible_user: olivier
  tasks:
  - include_tasks: software/apt-upgrade-tasks.yml
    tags: always

  - include_tasks: software/vim-task.yml
    tags: always

  - include_tasks: software/rust-task.yml
    tags: always

  - include_tasks: software/helm-task.yml
    tags: always
