---
# System package management - updates apt cache, lists upgradeable packages,
# performs full upgrade, and removes orphaned packages

  - name: update
    apt:
      cache_valid_time: 3600
      upgrade: no
    register: update_result
    retries: 5
    until: update_result is success
    

  - name: list upgradeable
    shell: apt list --upgradeable
    register: upgradeable
    

  - name: show update results
    debug: var=upgradeable.stdout_lines
    

  - name: upgrade
    apt:
      cache_valid_time: 3600
      install_recommends: no
      upgrade: yes
      autoclean: yes
    retries: 5
    register: upgrade_res
    until: upgrade_res is success
    

  - name: identify autoremove candidates
    shell: apt-get --dry-run autoremove | grep Remv || true
    register: autoremove_list
    

  - name: show autoremove candidates
    debug: var=autoremove_list.stdout_lines
    

  - name: Execute autoremove
    apt:
      autoremove: yes
    