---
- name: Install Infnoise package
  apt:
    name: infnoise
    state: present

- name: Check if Infnoise service is running
  command: systemctl is-active infnoise
  register: infnoise_status
  failed_when: false
  changed_when: false

- name: Enable and start Infnoise service (if not already running)
  service:
    name: infnoise
    enabled: yes
    state: started
  when: infnoise_status.stdout != "active"

- name: Check if Infnoise device is present
  command: infnoise -l
  register: infnoise_check
  failed_when: false
  changed_when: false

- name: Display Infnoise device status
  debug:
    msg: "{{ infnoise_check.stdout }}"
  when: infnoise_check.rc == 0

- name: Warn if no Infnoise device found
  debug:
    msg: "WARNING: No Infnoise device detected. Check USB connection."
  when: infnoise_check.rc != 0