---
# Prepares nodes for Longhorn distributed storage system - creates directories,
# installs dependencies, and validates storage mounts
- name: Prepare Longhorn storage directories
  tags: always
  block:
    - name: Create Longhorn data directory
      file:
        path: /data/longhorn
        state: directory
        owner: root
        group: root
        mode: '0755'
    
    - name: Install Longhorn prerequisites
      apt:
        name:
          - open-iscsi
          - util-linux
        state: present
        update_cache: yes
    
    - name: Enable and start iscsid service
      systemd:
        name: iscsid
        enabled: yes
        state: started
    
    - name: Check if /data is mounted
      command: mountpoint -q /data
      register: data_mounted
      failed_when: false
      changed_when: false
    
    - name: Display /data mount status
      debug:
        msg: "/data is {{ 'mounted' if data_mounted.rc == 0 else 'NOT mounted' }}"
    
    - name: Get /data disk usage
      command: df -h /data
      register: data_usage
      when: data_mounted.rc == 0
      changed_when: false
    
    - name: Display /data disk usage
      debug:
        var: data_usage.stdout_lines
      when: data_mounted.rc == 0
    
    - name: Ensure /data has proper permissions for Longhorn
      file:
        path: /data
        owner: root
        group: root
        mode: '0755'
      when: data_mounted.rc == 0