---
# Installs and configures Network Time Protocol (NTP) service for time synchronization
- name: Install NTP package
  apt:
    name: ntp
    state: present

- name: Enable and start NTP service
  service:
    name: ntp
    enabled: yes
    state: started