---
# Installs Smallstep Certificate Authority (step-ca) server with YubiKey support
# and systemd service configuration
# For Yubikey support step needs to be compiled with it enabled (disabled by default)
- name: Install step-ca
  apt:
    name: step-ca
    state: present

- name: Copy step-ca systemd service
  copy:
    src: files/step-ca.service
    dest: /etc/systemd/system/step-ca.service
    owner: root
    group: root
    mode: '0644'
  

- name: Copy step-ca binary with yubikey support
  copy:
    src: files/step-ca
    dest: /usr/local/bin/step-ca
    owner: root
    group: root
    mode: '0755'
  

- name: Set capability for step-ca to bind to privileged ports
  capabilities:
    path: /usr/local/bin/step-ca
    capability: cap_net_bind_service+eip
    state: present
  

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  
  
  