---
# Installs Smallstep CLI tool for certificate management and PKI operations
- name: Install base dependencies
  apt:
    name:
      - gpg
      - ca-certificates
    state: present
    install_recommends: no
    update_cache: yes

- name: Add Smallstep APT signing key
  get_url:
    url: https://packages.smallstep.com/keys/apt/repo-signing-key.gpg
    dest: /etc/apt/trusted.gpg.d/smallstep.asc
    mode: '0644'

- name: Add Smallstep APT repository
  copy:
    dest: /etc/apt/sources.list.d/smallstep.list
    content: |
      deb [signed-by=/etc/apt/trusted.gpg.d/smallstep.asc] https://packages.smallstep.com/stable/debian debs main
    mode: '0644'

- name: Update apt after adding Smallstep repo
  apt:
    update_cache: yes
  retries: 3
  delay: 5
  register: apt_update
  until: apt_update is succeeded

- name: Install step-cli
  apt:
    name: step-cli
    state: present
    update_cache: yes