---
# Installs Vim text editor and configures it with paste mode enabled by default
- name: Install vim
  apt:
    name: vim
    state: present
  

- name: Ensure 'set paste' is in Vim configuration
  lineinfile:
    path: /etc/vim/vimrc
    line: 'set paste'
    create: yes

