---
- name: Install vim
  apt:
    name: vim
    state: present
  tags: always

- name: Ensure 'set paste' is in Vim configuration
  lineinfile:
    path: /etc/vim/vimrc
    line: 'set paste'
    create: yes

