---
# Installs YubiKey management tools, PIV utilities, and configures step-ca
# systemd service for hardware security key integration
- name: Install Yubikey tools
  apt:
    name: yubikey-manager
    state: present
  

- name: Install Yubikey PIV tools
  apt:
    name: yubico-piv-tool 
    state: present
  

- name: Enable pcscd service
  systemd:
    name: pcscd.service
    enabled: yes
    state: started
    daemon_reload: yes
  

- name: Copy step-ca systemd service
  copy:
    src: files/step-ca.service
    dest: /etc/systemd/system/step-ca.service
    owner: root
    group: root
    mode: '0644'
  

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  

